name: test with next PHP version

on:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get PHP version
        id: php-version
        run: |
          echo "PHP_VERSION=`jq -r '.config.nextPhp' composer.json`" >> $GITHUB_ENV
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      - name: Restore Composer packages
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Save Composer packages
        id: cache-composer
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}

  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-next-php
      cancel-in-progress: true
    runs-on: ubuntu-24.04-arm
    needs: cache
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
#      - uses: dorny/paths-filter@v3
#        id: changes
#        with:
#          filters:
      - name: Check Docker Image Cache
        # uses: ScribeMD/docker-cache@0.5.0
        uses: AndreKurait/docker-cache  @0fe76702a40db986d9663c24954fc14c6a6031b7 # 0.6.0
        id: docker-cache
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('./.docker/compose.ci.yaml') }}
      - if: steps.docker-cache.outputs.cache-hit != 'true'
        name: Cache Docker Image
        run: task pullCiImages

  lint:
    runs-on: ubuntu-24.04-arm
    needs: cache
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Restore Composer packages
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
      - name: Get PHP version
        id: php-version
        run: |
          echo "PHP_VERSION=`jq -r '.config.nextPhp' composer.json`" >> $GITHUB_ENV
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
      - name: Restore Rector cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .tempCache/.rector
          key: rector-cache-${{ runner.os }}-${{ github.run_id }}-next-php
          restore-keys: |
            rector-cache-${{ runner.os }}-${{ github.run_id }}-next-php
      - name: Rector
        run: |
          composer rectorCheck
      - name: Cache .rector
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: .tempCache/.rector
          key: rector-cache-${{ runner.os }}-${{ github.run_id }}-next-php
      - name: Restore Stan cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .tempCache/.stan
          key: stan-cache-${{ runner.os }}-${{ github.run_id }}-next-php
          restore-keys: |
            stan-cache-${{ runner.os }}-${{ github.run_id }}-next-php
      - name: Stan
        run: |
          composer stanCheck
      - name: Cache .stan
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: .tempCache/.stan
          key: stan-cache-${{ runner.os }}-${{ github.run_id }}-next-php
      - name: Restore Ecs cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .tempCache/.ecs
          key: ecs-cache-${{ runner.os }}-${{ github.run_id }}-next-php
          restore-keys: |
            ecs-cache-${{ runner.os }}-${{ github.run_id }}-next-php
      - name: Ecs
        run: |
          composer ecsCheck
      - name: Cache .ecs
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: .tempCache/.ecs
          key: ecs-cache-${{ runner.os }}-${{ github.run_id }}-next-php
  test:
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Cache Docker images
        # uses: ScribeMD/docker-cache@0.5.0
        uses: AndreKurait/docker-cache@0fe76702a40db986d9663c24954fc14c6a6031b7 # 0.6.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('./.docker/compose.ci.yaml') }}
      - name: Restore Composer packages
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-cache-${{ runner.os }}-${{ runner.arch }}-next-php-${{ hashFiles('composer.lock') }}
      - name: Get PHP version
        id: php-version
        run: |
          echo "PHP_VERSION=`jq -r '.config.nextPhp' composer.json`" >> $GITHUB_ENV
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      - name: Setup
        run: |
          cp .docker/local/php/.env.ci .env
          task upOnCI
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
      - name: test
        run: composer phpunit
